### ISSUE TITLE
DrumCircle for BeOS

### ISSUE THREAD

**Issue by Begasus** [steffenyount/steffenyount.github.io#1]
Hello Steffen, not sure if you will receive this message, we have an open issue at haikuports where we collect recipes for Haiku ports.
Atm the issue can be found here: https://github.com/haikuports/haikuports/issues/646

Would be nice to know if you would consider donating the source to haikuarchives where we collect abbandoned(*) sources, in that way someone could see to revive some of your work. Granted there is a known license that permits them to use the source.

Greetings, Begasus aka Luc Schrijvers, packager for haikuports.

**Comment by steffenyount** [comment]
Projects added, licenses updated, responded in issue.

The new projects are here:
https://github.com/steffenyount/DrumCircle
https://github.com/steffenyount/PulsePlusPlus
